version: '3'

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  servers:

services:
  helixcore:
    volumes:
      - 'servers:/opt/perforce/servers'
    build:
      context: ./p4d
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    command:
      - /sbin/init
    image: p4d
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    ports:
      - "1666:1666"